modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${namespace}"
version="${version}"
displayName="${name}"
logoFile="${namespace}.png"
authors="${author}"
description='''
${description}
'''

[[dependencies.${namespace}]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${namespace}]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1]"
ordering="NONE"
side="BOTH"